"""
Main Orchestrator - Routes queries to appropriate agents
Enhanced with conversation history support for context-aware responses
"""

import sys
import os

current_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(current_dir)
sys.path.insert(0, parent_dir)

from agents.router_agent import RouterAgent
from agents.product_search_agent import ProductSearchAgent
from agents.compatibility_agent import CompatibilityAgent
from agents.troubleshooting_agent import TroubleshootingAgent
from agents.installation_agent import InstallationAgent
from agents.deepseek_client import DeepseekClient
from typing import Dict
import traceback


class ChatOrchestrator:
    def __init__(self):
        """Initialize all agents with error handling"""
        print("[Orchestrator] Initializing agents...")

        try:
            self.router = RouterAgent()
            self.product_search = ProductSearchAgent()
            self.compatibility = CompatibilityAgent()
            self.troubleshooting = TroubleshootingAgent()
            self.installation = InstallationAgent()
            self.deepseek_client = DeepseekClient()
            print("[Orchestrator] All agents initialized successfully!")
        except Exception as e:
            print(f"[Orchestrator] ERROR during initialization: {e}")
            traceback.print_exc()
            raise

    def handle_query(
        self, user_message: str, conversation_history: list = None
    ) -> Dict:
        """
        Main entry point - routes query to appropriate agent with error handling

        Args:
            user_message: User's query
            conversation_history: Optional list of previous messages with context

        Returns:
            Dict with response, agent used, and any additional data
        """
        print(f"\n[Orchestrator] Processing query: {user_message}")

        # Ensure conversation_history is a list
        if conversation_history is None:
            conversation_history = []

        # Input validation
        if not user_message or not user_message.strip():
            return {
                "response": "I didn't receive a message. Could you please ask your question?",
                "agent": "validation",
                "category": "VALIDATION_ERROR",
                "success": False,
            }

        try:
            # Route to appropriate agent
            category = self.router.route(user_message)
            print(f"[Orchestrator] Routed to category: {category}")

            result = None

            # Route to specific agent - NOW PASSING CONVERSATION HISTORY
            if category == "PRODUCT_SEARCH":
                result = self.product_search.handle_query(
                    user_message, conversation_history=conversation_history
                )

            elif category == "COMPATIBILITY_CHECK":
                result = self.compatibility.handle_query(
                    user_message, conversation_history=conversation_history
                )

            elif category == "INSTALLATION_HELP":
                result = self.installation.handle_query(
                    user_message, conversation_history=conversation_history
                )

            elif category == "TROUBLESHOOTING":
                result = self.troubleshooting.handle_query(
                    user_message, conversation_history=conversation_history
                )

            elif category == "ORDER_SUPPORT":
                result = {
                    "response": "For **order support**, **shipping questions**, or **returns**, please contact our customer service team:\n\n"
                    + "📞 **Phone:** 1-800-PARTSELECT\n"
                    + "💻 **Help Center:** partselect.com/help\n"
                    + "📧 **Email:** support@partselect.com\n\n"
                    + "I'm here to help with product information and technical support! 🔧",
                    "agent": "order_support",
                }

            elif category == "OUT_OF_SCOPE":
                result = self._handle_out_of_scope(user_message)

            else:
                # Fallback to product search with context
                print(
                    f"[Orchestrator] Unknown category '{category}', falling back to product search"
                )
                result = self.product_search.handle_query(
                    user_message, conversation_history=conversation_history
                )

            # Add metadata
            result["category"] = category
            result["success"] = True

            print(
                f"[Orchestrator] Response generated by {result.get('agent', 'unknown')} agent"
            )

            return result

        except Exception as e:
            print(f"[Orchestrator] ERROR: {e}")
            traceback.print_exc()

            return self._handle_error(user_message, str(e))

    def _handle_out_of_scope(self, user_message: str) -> Dict:
        """Handle queries outside the scope of refrigerator/dishwasher parts"""

        try:
            system_prompt = """You are a friendly PartSelect.com chat assistant.
The user asked a question that's outside your area of expertise (refrigerator and dishwasher parts).

Politely explain that you specialize in refrigerator and dishwasher parts, and redirect them to topics you can help with.

Keep it brief (2-3 sentences) and friendly."""

            response = self.deepseek_client.chat_with_system(
                system_prompt=system_prompt, user_message=user_message, temperature=0.7
            )

            return {"response": response, "agent": "out_of_scope"}

        except Exception as e:
            print(f"[Orchestrator] Error in out_of_scope handler: {e}")

            # Fallback response
            return {
                "response": "I specialize in helping with **refrigerator** and **dishwasher** parts. I can assist you with:\n\n"
                + "🔍 Finding the right parts\n"
                + "✅ Checking compatibility\n"
                + "🔧 Installation instructions\n"
                + "🛠️ Troubleshooting issues\n\n"
                + "What can I help you with today?",
                "agent": "out_of_scope",
            }

    def _handle_error(self, user_message: str, error_message: str) -> Dict:
        """
        Handle unexpected errors gracefully
        """
        # Check if it's a specific type of error
        if "timeout" in error_message.lower():
            response = "⏱️ The request timed out. This might be due to high server load. Please try again in a moment."
        elif "connection" in error_message.lower():
            response = "🔌 I'm having trouble connecting to the service. Please check your internet connection and try again."
        elif "api" in error_message.lower() or "deepseek" in error_message.lower():
            response = (
                "🤖 I'm experiencing issues with the AI service. Please try:\n\n"
                "1. Rephrasing your question\n"
                "2. Being more specific (e.g., include part numbers)\n"
                "3. Trying again in a moment"
            )
        else:
            # Generic error
            response = (
                "I apologize, but I encountered an unexpected error. Please try:\n\n"
                "1. **Rephrasing your question** - Be specific and include part/model numbers\n"
                "2. **Simple queries** - Try: 'Show me ice makers' or 'How do I install PS11752778?'\n"
                "3. **Contact support** - 1-800-PARTSELECT if the issue persists\n\n"
                "**What I can help with:**\n"
                "- Product search\n"
                "- Compatibility checks\n"
                "- Installation help\n"
                "- Troubleshooting"
            )

        return {
            "response": response,
            "agent": "error_handler",
            "category": "ERROR",
            "success": False,
            "error": error_message,
            "original_query": user_message,
        }


# Test function
def test_orchestrator():
    orchestrator = ChatOrchestrator()

    test_queries = [
        "Show me ice makers",
        "Is part PS11752778 compatible with WDT780SAEM1?",
        "How do I install PS11752778?",
        "My ice maker isn't working",
        "Where is my order?",
        "What's the weather today?",
        "Install PS99999999",
        "Is PS11752778 compatible?",
        "",
    ]

    print("\n" + "=" * 80)
    print("Testing Chat Orchestrator with Conversation History Support")
    print("=" * 80 + "\n")

    for query in test_queries:
        print(f"Query: '{query}'")
        result = orchestrator.handle_query(query)
        print(f"Category: {result.get('category', 'N/A')}")
        print(f"Agent: {result.get('agent', 'unknown')}")
        print(f"Success: {result.get('success', False)}")

        if result.get("error"):
            print(f"Error: {result['error']}")

        response = result.get("response", "No response")
        print(f"Response: {response[:150]}{'...' if len(response) > 150 else ''}")
        print("\n" + "=" * 80 + "\n")


if __name__ == "__main__":
    test_orchestrator()
